@startuml
title UML-діаграма активності парсингу секції досвіду

start

:Отримати блоки секції досвіду;
:Об'єднати блоки в текст секції досвіду;
:Розбити секцію на кандидатні записи про роботу;

repeat
  :Взяти наступний кандидатний запис;
  :Витягти текст поточного кандидатного запису;
  :Розбити запис на рядки;
  :Визначити рядки заголовка\nта описові рядки;

  :Шукати діапазон дат у заголовку\nабо в тексті запису;

  if (Діапазон дат знайдено?) then (так)
    :Зберегти дату початку,\nдату завершення і вихідний діапазон дат;
  else (ні)
    :Продовжити без полів дат;
  endif

  :Проаналізувати рядки заголовка і визначити\nкомпанію, посаду та локацію;

  :Відокремити марковані пункти\nвід звичайного описового тексту;

  if (Марковані пункти знайдено?) then (так)
    :Зберегти марковані пункти;
  else (ні)
    :Продовжити без маркованих пунктів;
  endif

  if (Залишився описовий текст?) then (так)
    :Зберегти решту тексту як опис;
  else (ні)
    :Продовжити без описового тексту;
  endif

  :Створити структурований запис досвіду;
  :Додати запис до списку розпарсеного досвіду;

repeat while (Є ще кандидатні записи?) is (так)

if (Надійні записи досвіду знайдено?) then (так)
  :Повернути розпарсені записи досвіду;
else (ні)
  :Зберегти вихідний текст досвіду\nдля fallback-обробки;
endif

stop
@enduml
