@startuml
title UML-діаграма активності аналізу заголовка запису досвіду

start

:Отримати рядки заголовка\nпоточного запису досвіду;
:Знайти діапазон дат і прибрати його\nіз тексту заголовка;

if (Діапазон дат знайдено?) then (так)
  :Зберегти вихідний діапазон дат;
else (ні)
  :Продовжити без значення дати;
endif

:Перевірити рядок, схожий на компанію;
:Перевірити шаблон назви посади;
:Перевірити шаблон локації;
:Призначити виявлені значення\nкомпанії, посаді та локації;

if (Залишився невідомий текст?) then (так)
  :Перенести невідомі фрагменти\nдо решти тексту запису;
else (ні)
endif

:Повернути класифіковані поля заголовка;
stop
@enduml
