@startuml
title Resume Parser Service - Use Case Diagram

left to right direction
skinparam shadowing false

actor "API Gateway" as Gateway
actor "Frontend Developer" as FrontendDev

rectangle "Resume Parser Service" {
  usecase "Parse uploaded resume" as UCParse
  usecase "Get content contract" as UCContract
  usecase "View API documentation" as UCDocs
}

Gateway --> UCParse
FrontendDev --> UCContract
FrontendDev --> UCDocs

@enduml
